+define+SYNTHESIS
+incdir+rtl/ibex/rtl
+incdir+rtl/ibex/vendor/lowrisc_ip/ip/prim/rtl
+incdir+rtl/ibex/vendor/lowrisc_ip/ip/prim_generic/rtl
+incdir+rtl/ibex/vendor/lowrisc_ip/dv/sv/dv_utils

rtl/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_mubi_pkg.sv
rtl/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_cipher_pkg.sv
rtl/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_util_pkg.sv
rtl/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_count_pkg.sv
rtl/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_pkg.sv
rtl/ibex/vendor/lowrisc_ip/ip/prim_generic/rtl/prim_pkg.sv
rtl/ibex/vendor/lowrisc_ip/ip/prim_generic/rtl/prim_ram_1p_pkg.sv

rtl/ibex/vendor/lowrisc_ip/ip/prim_generic/rtl/prim_and2.sv
rtl/ibex/vendor/lowrisc_ip/ip/prim_generic/rtl/prim_buf.sv
rtl/ibex/vendor/lowrisc_ip/ip/prim_generic/rtl/prim_clock_gating.sv
rtl/ibex/vendor/lowrisc_ip/ip/prim_generic/rtl/prim_clock_mux2.sv
rtl/ibex/vendor/lowrisc_ip/ip/prim_generic/rtl/prim_flop.sv
rtl/ibex/vendor/lowrisc_ip/ip/prim_generic/rtl/prim_ram_1p.sv

rtl/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_count.sv
rtl/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_lfsr.sv
rtl/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_onehot_check.sv
rtl/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_onehot_enc.sv
rtl/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_onehot_mux.sv
rtl/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_ram_1p_scr.sv
rtl/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_28_22_dec.sv
rtl/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_28_22_enc.sv
rtl/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_39_32_dec.sv
rtl/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_39_32_enc.sv
rtl/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_39_32_dec.sv
rtl/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_39_32_enc.sv

rtl/ibex/rtl/ibex_pkg.sv
rtl/ibex/rtl/ibex_alu.sv
rtl/ibex/rtl/ibex_branch_predict.sv
rtl/ibex/rtl/ibex_compressed_decoder.sv
rtl/ibex/rtl/ibex_controller.sv
rtl/ibex/rtl/ibex_csr.sv
rtl/ibex/rtl/ibex_cs_registers.sv
rtl/ibex/rtl/ibex_counter.sv
rtl/ibex/rtl/ibex_decoder.sv
rtl/ibex/rtl/ibex_dummy_instr.sv
rtl/ibex/rtl/ibex_ex_block.sv
rtl/ibex/rtl/ibex_fetch_fifo.sv
rtl/ibex/rtl/ibex_icache.sv
rtl/ibex/rtl/ibex_id_stage.sv
rtl/ibex/rtl/ibex_if_stage.sv
rtl/ibex/rtl/ibex_load_store_unit.sv
rtl/ibex/rtl/ibex_multdiv_fast.sv
rtl/ibex/rtl/ibex_multdiv_slow.sv
rtl/ibex/rtl/ibex_pmp.sv
rtl/ibex/rtl/ibex_prefetch_buffer.sv
rtl/ibex/rtl/ibex_wb_stage.sv
rtl/ibex/rtl/ibex_core.sv
rtl/ibex/rtl/ibex_register_file_ff.sv
rtl/ibex/rtl/ibex_register_file_fpga.sv
rtl/ibex/rtl/ibex_register_file_latch.sv
rtl/ibex/rtl/ibex_lockstep.sv
rtl/ibex/rtl/ibex_top.sv
